# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "octokit", "~> 4.0"

group :development do
  gem "pry-byebug"
end
